name: plotsense-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - jupyter
  - matplotlib>=3.8.0
  - seaborn>=0.11
  - pandas>=1.0
  - numpy
  - scipy
  - scikit-learn
  - pip:
    - plotsense
    - groq
    - python-dotenv